### PR TITLE
Add history type filter to group history

### LINKED ISSUE #2635: Add history type filter to history page
With larger groups, it becomes cumbersome to find out who did what when looking at the general history. A filter with the history types should be added to the history page.

### PR DESCRIPTION
**Pull request by nicksellen**
Closes #2635

## What does this PR do?

Adds history type filter to group history page. History types are new translations, as our existing ones are parametrized for specific history entries.

I didn't add the filter to the other history pages, although arguably would be useful on the place one at least... but maybe this is useful enough for now.

Video walk through:

https://user-images.githubusercontent.com/31616/231243271-e46d3223-c28f-4000-bb7e-fd9e500ae209.mp4

## Checklist

- [ ] added a test, or explain why one is not needed/possible...
- [ ] no unrelated changes
- [ ] asked someone for a code review
- [ ] joined [#karrot:matrix.org](https://matrix.to/#/#karrot:matrix.org)
- [ ] added an entry to CHANGELOG.md (description, pull request link, username(s))
- [ ] tried out on a mobile device (does everything work as expected on a smaller screen?)

### CODE REVIEW

**Comment by nicksellen** [comment]
@dwaxweiler do you want to see if this would meet your needs? (as I say in the description, it's only on the group history page, not other history pages), check the video above!

**Comment by dwaxweiler** [comment]
@nicksellen yes, this looks good! :)

**Review by tiltec — APPROVED** [review]
Looks good!

Might be easy to add to the place history page as well? For the user history, don't know how well it fits the layout.

**Comment by nicksellen** [comment]
I added it for place history now too :) Will merge if this passes

**Pull request merged**
